# (C) Copyright 2024 Hewlett Packard Enterprise Development LP
services:

  nats-box:
    hostname: nats-box
    container_name: nats-box
    image: natsio/nats-box:0.14.0
    command: ["/bin/ash", "/usr/local/bin/nats-box-entrypoint.sh"]
    volumes:
    - ./nats_configs/scripts/:/user_scripts
    - ./nats_configs/nsc:/nsc
    - ./nats_configs/scripts/nats-box-entrypoint.sh:/usr/local/bin/nats-box-entrypoint.sh
    env_file:
    - ./nats_configs/.env

  nats-server:
    hostname: nats-server
    container_name: nats-server
    image: nats:2.10.0
    entrypoint: /nats-server
    command: "-c /etc/nats/conf/server.conf -js -m 8222"
    ports:
    - "4222"
    - "8222"
    volumes:
    - ./nats_configs/creds/:/etc/nats/jwt
    - ./nats_configs/server_configs/:/etc/nats/conf
    env_file:
    - ./nats_configs/.env
