version: "3.3"
services:
  cds-proto-dev:
    hostname: cds-proto-dev
    container_name: cds-proto-dev
    image: ghcr.io/hpe-cds/containers-images/cds-proto-dev:latest
    pull_policy: always
    privileged: true
    environment:
      - HTTP_PROXY
      - http_proxy
      - HTTPS_PROXY
      - https_proxy
      - NO_PROXY
      - no_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.kube/config:/home/dev/.kube/config
      - $HOME/.gitconfig:/home/dev/.gitconfig
      - $HOME/.ssh:/home/dev/.ssh
      - ${CDSDEV_MNT:-.}:/home/dev/ws
    ports:
      - "22"
      - "5000-5005"
      - "3000"
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - echo hello
      interval: 30s
      timeout: 5s
      retries: 3
